language: node_js

branches:
  only:
  - master

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull

install: npm install -g npm@6

script: npm run test:unit