language: node_js
node_js:
  - 12

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull

install:
  - npm install

script:
  - npm run test