language: node_js
node_js:
  - 12

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull

install:
  - npm install

script:
  - npm run test
  - ./node_modules/.bin/codecov --token="897cb93c-3b5b-464a-b426-85e5e5d75909"