language: node_js
node_js:
  - 12

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull

install:
  - npm install

script:
  - npm run test
  - ./node_modules/.bin/codecov --token="0117898f-8434-4a1d-83dc-7218f7b5eda4"